spotlights:
  staging:
    subnets:
      load_balancer:
        - ap-northeast-1c
      gateway:
        - ap-northeast-1c
      web:
        - ap-northeast-1c
      database:
        - ap-northeast-1b
        - ap-northeast-1c
    rds:
      allocated_storage: 5 # GB
      instance_class: db.t1.micro
      multi_az: false
      availability_zone: ap-northeast-1c
